package utils

var FakeStudentInfo StudentInfoType = StudentInfoType{
	ID: "123456",
	Name: "Doe, Jonh Thomas",
	Birthdate: "12/24/2003",
	Campus: "Heritage High School",
	Grade: "12",
	Counselor: "NELSON-MOON, LANNIS",
}

var FakeStudentGPAs StudentGPAType = StudentGPAType{
	WeightedGPA: "5.0500",
	UnweightedGPA: "3.8800",
}

var FakeStudentSchedule []StudentScheduleType = []StudentScheduleType{
	{
		Building: "Heritage High School",
      	Code: "MTH45300A - 1",
      	Name: "AP Calculus AB S1",
      	Days: "A",
      	MarkingPeriods: "Q1, Q2",
      	Periods: "1",
      	Room: "C112",
      	Status: "Active",
      	Teacher: "Poltl, Beth",
	},
	{
		Building: "Heritage High School",
		Code: "SCI43300A - 1",
		Name: "AP Environmental Science S1",
		Days: "B",
		MarkingPeriods: "Q1, Q2",
		Periods: "1",
		Room: "C202",
		Status: "Active",
		Teacher: "GLENDENNING, SHAREE",
	},
	{
		Building: "Heritage High School",
      	Code: "MTH45300B - 1",
      	Name: "AP Calculus AB S2",
      	Days: "A",
      	MarkingPeriods: "Q3, Q4",
      	Periods: "1",
      	Room: "C112",
      	Status: "Active",
      	Teacher: "Poltl, Beth",
	},
	{
		Building: "Heritage High School",
      	Code: "SCI43300B - 1",
      	Name: "AP Environmental Science S2",
      	Days: "B",
      	MarkingPeriods: "Q3, Q4",
      	Periods: "1",
      	Room: "C202",
      	Status: "Active",
      	Teacher: "GLENDENNING, SHAREE",
	},
	{
		Building: "Heritage High School",
      	Code: "SST34310 - 3",
      	Name: "AP Economics",
      	Days: "A",
      	MarkingPeriods: "Q1, Q2",
      	Periods: "2",
      	Room: "C117",
      	Status: "Active",
      	Teacher: "Dempsey, Patricia",
	},
	{
		Building: "Heritage High School",
      	Code: "ELA14300A - 4",
      	Name: "AP English Literature S1",
      	Days: "B",
      	MarkingPeriods: "Q1, Q2",
      	Periods: "2",
      	Room: "B115",
      	Status: "Active",
      	Teacher: "SHASKAN, ATTICUS",
	},
	{
		Building: "Heritage High School",
		Code: "SST34300 - 4",
		Name: "AP Government",
		Days: "A",
		MarkingPeriods: "Q3, Q4",
		Periods: "2",
		Room: "C116",
		Status: "Active",
		Teacher: "Huggins, Jonathan",
	  },
	  {
		Building: "Heritage High School",
		Code: "ELA14300B - 4",
		Name: "AP English Literature S2",
		Days: "B",
		MarkingPeriods: "Q3, Q4",
		Periods: "2",
		Room: "B115",
		Status: "Active",
		Teacher: "SHASKAN, ATTICUS",
	  },
	  {
		Building: "Heritage High School",
		Code: "CATE36400A - 1",
		Name: "Prac News Prod 2 S1",
		Days: "A",
		MarkingPeriods: "Q1, Q2",
		Periods: "3",
		Room: "A123",
		Status: "Active",
		Teacher: "BAGWELL, CANDACE",
	  },
	  {
		Building: "CTE",
		Code: "CATE27600A - 3",
		Name: "Mobile App Programming S1@CTEC",
		Days: "B",
		MarkingPeriods: "Q1, Q2",
		Periods: "3",
		Room: "XC148",
		Status: "Active",
		Teacher: "BUNN, BRYAN",
	  },
	  {
		Building: "Heritage High School",
		Code: "CATE36400B - 1",
		Name: "Prac News Prod 2 S2",
		Days: "A",
		MarkingPeriods: "Q3, Q4",
		Periods: "3",
		Room: "A123",
		Status: "Active",
		Teacher: "BAGWELL, CANDACE",
	  },
	  {
		Building: "CTE",
		Code: "CATE27600B - 3",
		Name: "Mobile App Programming S2@CTEC",
		Days: "B",
		MarkingPeriods: "Q3, Q4",
		Periods: "3",
		Room: "XC148",
		Status: "Active",
		Teacher: "BUNN, BRYAN",
	  },
	  {
		Building: "Heritage High School",
		Code: "REL99013A - 1",
		Name: "Rel 4A OR 4B S1",
		Days: "A",
		MarkingPeriods: "Q1, Q2",
		Periods: "4",
		Room: "N/A",
		Status: "Active",
		Teacher: "Staff",
	  },
	  {
		Building: "Heritage High School",
		Code: "MTH45310A - 4",
		Name: "AP Statistics S1",
		Days: "B",
		MarkingPeriods: "Q1, Q2",
		Periods: "4",
		Room: "C108",
		Status: "Active",
		Teacher: "Davenport, Aimee",
	  },
	  {
		Building: "Heritage High School",
		Code: "REL99013B - 1",
		Name: "Rel 4A OR 4B S2",
		Days: "A",
		MarkingPeriods: "Q3, Q4",
		Periods: "4",
		Room: "N/A",
		Status: "Active",
		Teacher: "Staff",
	  },
	  {
		Building: "Heritage High School",
		Code: "MTH45310B - 4",
		Name: "AP Statistics S2",
		Days: "B",
		MarkingPeriods: "Q3, Q4",
		Periods: "4",
		Room: "C108",
		Status: "Active",
		Teacher: "Davenport, Aimee",
	  },
	  {
		Building: "Heritage High School",
		Code: "MSC15136M - 12",
		Name: "12th Grade Advisory GP1",
		Days: "A, B",
		MarkingPeriods: "Q1, Q2, Q3, Q4",
		Periods: "ADV",
		Room: "C218",
		Status: "Active",
		Teacher: "O'brien, TIMOTHY",
	  },
}

var FakeStudentCurrentClasses []StudentCourseType = []StudentCourseType{
	{
		LastUpdated: "", 
		Assignments: []StudentAssignmentType{  },
		Credits: "1",
		Grade: "98",
		Name: "CATE27600B - 3    Mobile App Programming S2@CTEC",
		Weight: "6",
	},
	{
		LastUpdated: "1/6/2022",
		Assignments: []StudentAssignmentType{
		  {
			Assignment: "PA Script #3",
			Category: "Minor Grades",
			DateAssigned: "02/09/2022",
			DateDue: "03/04/2022",
			Score: "100",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Social Media Posts",
			Category: "Minor Grades",
			DateAssigned: "01/04/2022",
			DateDue: "03/02/2022",
			Score: "100",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "MP3 Package/Segment #2",
			Category: "Major Grades",
			DateAssigned: "01/10/2022",
			DateDue: "03/02/2022",
			Score: "95",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Event Coverage",
			Category: "Major Grades",
			DateAssigned: "01/04/2022",
			DateDue: "02/25/2022",
			Score: "100",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "PA Script #2",
			Category: "Minor Grades",
			DateAssigned: "01/24/2022",
			DateDue: "02/08/2022",
			Score: "98",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "MP3 Package/Segment #1",
			Category: "Major Grades",
			DateAssigned: "01/11/2022",
			DateDue: "02/04/2022",
			Score: "95",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "PA Script #1",
			Category: "Minor Grades",
			DateAssigned: "01/04/2022",
			DateDue: "01/21/2022",
			Score: "97.00",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "MP3 Calendar Check",
			Category: "Non-graded",
			DateAssigned: "01/04/2022",
			DateDue: "01/06/2022",
			Score: "100.0",
			TotalPoints: "100.00",
		  },
		},
		Credits: "1",
		Grade: "92",
		Name: "CATE36400B - 1    Prac News Prod 2 S2",
		Weight: "5",
	  },
	  {
		LastUpdated: "1/13/2022",
		Assignments: []StudentAssignmentType{
		  {
			Assignment: "Thesis Practice #1",
			Category: "Non-graded",
			DateAssigned: "",
			DateDue: "01/13/2022",
			Score: "90.00",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Christmas Carol Q3 Essay",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "01/05/2022",
			Score: "80.00",
			TotalPoints: "100.00",
		  },
		},
		Credits: "1",
		Grade: "85.00",
		Name: "ELA14300B - 4    AP English Literature S2",
		Weight: "6",
	  },
	  {
		LastUpdated: "1/10/2022",
		Assignments: []StudentAssignmentType{
		  {
			Assignment: "Unit 6 Test (Integration)",
			Category: "Major Grades",
			DateAssigned: "",
			DateDue: "02/08/2022",
			Score: "85",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Delta Math Practice (Unit 6)",
			Category: "Non-graded",
			DateAssigned: "",
			DateDue: "02/08/2022",
			Score: "100",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Quiz 4 (Antiderivatives and Rules of Integration)",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "01/31/2022",
			Score: "97",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Quiz 3 (FTC and Definite Integrals)",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "01/27/2022",
			Score: "95",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Quiz 2 (Properties of Def. Integrals)",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "01/25/2022",
			Score: "75",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Quiz 1 (Reimann Sums and Definite Integrals)",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "01/19/2022",
			Score: "75",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Unit 5 Test (Analytical Applications of Derivatives)",
			Category: "Major Grades",
			DateAssigned: "",
			DateDue: "01/10/2022",
			Score: "97.00",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Delta Math Practice (Unit 5)",
			Category: "Non-graded",
			DateAssigned: "",
			DateDue: "01/10/2022",
			Score: "85.00",
			TotalPoints: "100.00",
		  },
		},
		Credits: "1",
		Grade: "80.80",
		Name: "MTH45300B - 1    AP Calculus AB S2",
		Weight: "6",
	  },
	  {
		LastUpdated: "",
		Assignments: []StudentAssignmentType{
		  {
			Assignment: "Test - 8 Confidence Intervals",
			Category: "Major Grades",
			DateAssigned: "",
			DateDue: "01/26/2022",
			Score: "98",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Skills Check - 8 Confidence Intervals",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "01/24/2022",
			Score: "100",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Practice - 8.3 (canvas)",
			Category: "Non-graded",
			DateAssigned: "",
			DateDue: "01/24/2022",
			Score: "98",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Practice - 8.2 (canvas)",
			Category: "Non-graded",
			DateAssigned: "",
			DateDue: "01/24/2022",
			Score: "100",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Practice - 8.1 (canvas)",
			Category: "Non-graded",
			DateAssigned: "",
			DateDue: "01/24/2022",
			Score: "93",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Group Skills Check - 7 Sampling Distributions",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "01/11/2022",
			Score: "",
			TotalPoints: "50.00",
		  },
		},
		Credits: "1",
		Grade: "0.00",
		Name: "MTH45310B - 4    AP Statistics S2",
		Weight: "6",
	  },
	  {
		LastUpdated: "",
		Assignments: []StudentAssignmentType{  },
		Credits: "1",
		Grade: "90",
		Name: "SCI43300B - 1    AP Environmental Science S2",
		Weight: "6",
	  },
	  {
		LastUpdated: "",
		Assignments: []StudentAssignmentType{
		  {
			Assignment: "Midterm Exam (Units 1 & 2)",
			Category: "Major Grades",
			DateAssigned: "",
			DateDue: "02/23/2022",
			Score: "98",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Unit 2 Major Grade FRQ",
			Category: "Major Grades",
			DateAssigned: "",
			DateDue: "02/16/2022",
			Score: "100.00",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Unit 2 MC Quiz",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "02/14/2022",
			Score: "98",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Unit 2 Argument FRQ Practice",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "02/11/2022",
			Score: "105",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Unit 2 Congress FRQ Practice",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "02/04/2022",
			Score: "100",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Unit 1 Major Grade FRQ",
			Category: "Major Grades",
			DateAssigned: "",
			DateDue: "01/21/2022",
			Score: "98",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Unit 1 MC Quiz",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "01/21/2022",
			Score: "87",
			TotalPoints: "100.00",
		  },
		  {
			Assignment: "Unit 1 Concept Application & Argument FRQ Practice",
			Category: "Minor Grades",
			DateAssigned: "",
			DateDue: "01/14/2022",
			Score: "",
			TotalPoints: "100.00",
		  },
		},
		Credits: "1",
		Grade: "0.00",
		Name: "SST34300 - 4    AP Government",
		Weight: "6",
	  },
}